volumes:
  quanly-pk-be-service-db-data:
  certs:
    external: true
  vhost.d:
  html:

services:
  quanly-pk-be-service-db:
    image: postgres:15
    platform: linux/x86_64
    container_name: quanly-pk-be-service-db
    ports:
      - '${DB_PORT}:5432'
    environment:
      TZ: UTC
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: always
    volumes:
      - quanly-pk-be-service-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}']
      timeout: 20s
      retries: 10
    networks:
      - gasy-network

  quanly-pk-be-service:
    build:
      dockerfile: Dockerfile
    image: quanly-pk-be-service:latest
    container_name: quanly-pk-be-service
    depends_on:
      - quanly-pk-be-service-db
    ports:
      - '${PORT}:${PORT}'
    restart: always
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      PORT: ${PORT}
      ADMIN_NOTIFY_EMAIL: ${ADMIN_NOTIFY_EMAIL}

      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      SECRETKEY: ${SECRETKEY}
      EXPIRESIN: ${EXPIRESIN}

      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT:-9003}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SECURE: ${MAIL_SECURE}
      MAIL_USER: ${MAIL_USER}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

      CORS_ORIGINS: ${CORS_ORIGINS}
      HTTPS_METHOD: ${HTTPS_METHOD}

      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_CONTAINER_NAME: ${AZURE_STORAGE_CONTAINER_NAME}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
    networks:
      - gasy-network

networks:
  gasy-network:
    name: gasy-network
    external: true
